### ISSUE TITLE
Static IP Different From RTP IP

### ISSUE THREAD

**Issue by xpresslogistics2015** [voxserv/kamailio-static-relay#1]
Hi 
Nice work, I am trying to implement this kamailio-static-relay. How would I implement it if the rtp ip is not the same as the sip ip?

Thanks a lot.

**Comment by ssinyagin** [comment]
you can install rtpengine on your media servers and make kamailio talk to them. Also you can use Dispatcher module to distribute the load to multiple back-end servers. There are lots of possibilities. Unfortunately I cannot share all my configs because of NDA.

**Comment by xpresslogistics2015** [comment]
Thanks a lot. Unfortunately I have no control over both sip servers - just the relay. Thanks again.

**Comment by ssinyagin** [comment]
If you have a budget, we can negotiate a deal. There's a fully featured kamalilio dispatcher with load balancing, per-destination number routing, fallback, and rtpengine. The customer is not against compensating the design costs.
